// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_botfather from "./routes/api/botfather.ts";
import * as $api_retrieveGroups from "./routes/api/retrieveGroups.ts";
import * as $api_sendMessage from "./routes/api/sendMessage.ts";
import * as $api_sendSuggestion from "./routes/api/sendSuggestion.ts";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $privacy from "./routes/privacy.tsx";
import * as $success from "./routes/success.tsx";
import * as $suggest from "./routes/suggest.tsx";
import * as $webapp_layout from "./routes/webapp/_layout.tsx";
import * as $webapp_api_manageGroups from "./routes/webapp/api/manageGroups.ts";
import * as $webapp_api_validate from "./routes/webapp/api/validate.ts";
import * as $webapp_contact from "./routes/webapp/contact.tsx";
import * as $webapp_current_groups from "./routes/webapp/current_groups.tsx";
import * as $webapp_deleted_groups from "./routes/webapp/deleted_groups.tsx";
import * as $webapp_pending_groups from "./routes/webapp/pending_groups.tsx";
import * as $webapp_success from "./routes/webapp/success.tsx";
import * as $webapp_suggest from "./routes/webapp/suggest.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $DarkModeSwitch from "./islands/DarkModeSwitch.tsx";
import * as $GroupsList from "./islands/GroupsList.tsx";
import * as $HeaderNav from "./islands/HeaderNav.tsx";
import * as $PostsList from "./islands/PostsList.tsx";
import * as $SuggestForm from "./islands/SuggestForm.tsx";
import * as $webapp_ContactForm from "./islands/webapp/ContactForm.tsx";
import * as $webapp_CurrentGroupsList from "./islands/webapp/CurrentGroupsList.tsx";
import * as $webapp_DeletedGroupsList from "./islands/webapp/DeletedGroupsList.tsx";
import * as $webapp_GroupEditCard from "./islands/webapp/GroupEditCard.tsx";
import * as $webapp_GroupRecoverCard from "./islands/webapp/GroupRecoverCard.tsx";
import * as $webapp_InitializeWebApp from "./islands/webapp/InitializeWebApp.tsx";
import * as $webapp_PendingGroupsList from "./islands/webapp/PendingGroupsList.tsx";
import * as $webapp_Success from "./islands/webapp/Success.tsx";
import * as $webapp_SuggestForm from "./islands/webapp/SuggestForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/api/botfather.ts": $api_botfather,
    "./routes/api/retrieveGroups.ts": $api_retrieveGroups,
    "./routes/api/sendMessage.ts": $api_sendMessage,
    "./routes/api/sendSuggestion.ts": $api_sendSuggestion,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/privacy.tsx": $privacy,
    "./routes/success.tsx": $success,
    "./routes/suggest.tsx": $suggest,
    "./routes/webapp/_layout.tsx": $webapp_layout,
    "./routes/webapp/api/manageGroups.ts": $webapp_api_manageGroups,
    "./routes/webapp/api/validate.ts": $webapp_api_validate,
    "./routes/webapp/contact.tsx": $webapp_contact,
    "./routes/webapp/current_groups.tsx": $webapp_current_groups,
    "./routes/webapp/deleted_groups.tsx": $webapp_deleted_groups,
    "./routes/webapp/pending_groups.tsx": $webapp_pending_groups,
    "./routes/webapp/success.tsx": $webapp_success,
    "./routes/webapp/suggest.tsx": $webapp_suggest,
  },
  islands: {
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/DarkModeSwitch.tsx": $DarkModeSwitch,
    "./islands/GroupsList.tsx": $GroupsList,
    "./islands/HeaderNav.tsx": $HeaderNav,
    "./islands/PostsList.tsx": $PostsList,
    "./islands/SuggestForm.tsx": $SuggestForm,
    "./islands/webapp/ContactForm.tsx": $webapp_ContactForm,
    "./islands/webapp/CurrentGroupsList.tsx": $webapp_CurrentGroupsList,
    "./islands/webapp/DeletedGroupsList.tsx": $webapp_DeletedGroupsList,
    "./islands/webapp/GroupEditCard.tsx": $webapp_GroupEditCard,
    "./islands/webapp/GroupRecoverCard.tsx": $webapp_GroupRecoverCard,
    "./islands/webapp/InitializeWebApp.tsx": $webapp_InitializeWebApp,
    "./islands/webapp/PendingGroupsList.tsx": $webapp_PendingGroupsList,
    "./islands/webapp/Success.tsx": $webapp_Success,
    "./islands/webapp/SuggestForm.tsx": $webapp_SuggestForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
