// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_botfather from "./routes/api/botfather.ts";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_faqs from "./routes/api/faqs.ts";
import * as $api_groups from "./routes/api/groups.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_register from "./routes/api/register.ts";
import * as $api_suggest from "./routes/api/suggest.ts";
import * as $contact from "./routes/contact.tsx";
import * as $dashboard_layout from "./routes/dashboard/_layout.tsx";
import * as $dashboard_api_contacts from "./routes/dashboard/api/contacts.ts";
import * as $dashboard_api_faqs from "./routes/dashboard/api/faqs.ts";
import * as $dashboard_api_groups from "./routes/dashboard/api/groups.ts";
import * as $dashboard_api_suggestions from "./routes/dashboard/api/suggestions.ts";
import * as $dashboard_faqs from "./routes/dashboard/faqs.tsx";
import * as $dashboard_groups from "./routes/dashboard/groups.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_messages from "./routes/dashboard/messages.tsx";
import * as $dashboard_suggestions from "./routes/dashboard/suggestions.tsx";
import * as $erasmus_slug_ from "./routes/erasmus/[slug].tsx";
import * as $erasmus_index from "./routes/erasmus/index.tsx";
import * as $faqs from "./routes/faqs.tsx";
import * as $index from "./routes/index.tsx";
import * as $register from "./routes/register.tsx";
import * as $success from "./routes/success.tsx";
import * as $suggest from "./routes/suggest.tsx";
import * as $AdminForm from "./islands/AdminForm.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $FaqsDir from "./islands/FaqsDir.tsx";
import * as $FaqsPanel from "./islands/FaqsPanel.tsx";
import * as $GroupsDir from "./islands/GroupsDir.tsx";
import * as $GroupsPanel from "./islands/GroupsPanel.tsx";
import * as $MessagesForm from "./islands/MessagesForm.tsx";
import * as $MessagesPanel from "./islands/MessagesPanel.tsx";
import * as $PostsDir from "./islands/PostsDir.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import * as $SuggestionsForm from "./islands/SuggestionsForm.tsx";
import * as $SuggestionsPanel from "./islands/SuggestionsPanel.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/botfather.ts": $api_botfather,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/faqs.ts": $api_faqs,
    "./routes/api/groups.ts": $api_groups,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/register.ts": $api_register,
    "./routes/api/suggest.ts": $api_suggest,
    "./routes/contact.tsx": $contact,
    "./routes/dashboard/_layout.tsx": $dashboard_layout,
    "./routes/dashboard/api/contacts.ts": $dashboard_api_contacts,
    "./routes/dashboard/api/faqs.ts": $dashboard_api_faqs,
    "./routes/dashboard/api/groups.ts": $dashboard_api_groups,
    "./routes/dashboard/api/suggestions.ts": $dashboard_api_suggestions,
    "./routes/dashboard/faqs.tsx": $dashboard_faqs,
    "./routes/dashboard/groups.tsx": $dashboard_groups,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/dashboard/messages.tsx": $dashboard_messages,
    "./routes/dashboard/suggestions.tsx": $dashboard_suggestions,
    "./routes/erasmus/[slug].tsx": $erasmus_slug_,
    "./routes/erasmus/index.tsx": $erasmus_index,
    "./routes/faqs.tsx": $faqs,
    "./routes/index.tsx": $index,
    "./routes/register.tsx": $register,
    "./routes/success.tsx": $success,
    "./routes/suggest.tsx": $suggest,
  },
  islands: {
    "./islands/AdminForm.tsx": $AdminForm,
    "./islands/Chart.tsx": $Chart,
    "./islands/FaqsDir.tsx": $FaqsDir,
    "./islands/FaqsPanel.tsx": $FaqsPanel,
    "./islands/GroupsDir.tsx": $GroupsDir,
    "./islands/GroupsPanel.tsx": $GroupsPanel,
    "./islands/MessagesForm.tsx": $MessagesForm,
    "./islands/MessagesPanel.tsx": $MessagesPanel,
    "./islands/PostsDir.tsx": $PostsDir,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/SuggestionsForm.tsx": $SuggestionsForm,
    "./islands/SuggestionsPanel.tsx": $SuggestionsPanel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
